<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>pitTeam</RootNamespace>
        <AssemblyName>pitFireTeam</AssemblyName>
        <Version>0.9.2</Version>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);CS0618;CS0649;CS8600;CS8601;CS8602;CS8604;CS8618;CS8620;CS8625</NoWarn>
        <Deterministic>true</Deterministic>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="0Harmony">
            <HintPath>libs\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="Assembly-CSharp, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="ConfigurationManager">
            <HintPath>libs\ConfigurationManager.dll</HintPath>
        </Reference>
        <Reference Include="ItemTemplate.Types, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\ItemTemplate.Types.dll</HintPath>
        </Reference>
        <Reference Include="spt-common">
            <HintPath>libs\spt-common.dll</HintPath>
        </Reference>
        <Reference Include="spt-custom">
            <HintPath>libs\spt-custom.dll</HintPath>
        </Reference>
        <Reference Include="spt-prepatch">
            <HintPath>libs\spt-prepatch.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx">
            <HintPath>libs\BepInEx.dll</HintPath>
        </Reference>
        <Reference Include="bsg.console.core">
            <HintPath>libs\bsg.console.core.dll</HintPath>
        </Reference>
        <Reference Include="Comfort">
            <HintPath>libs\Comfort.dll</HintPath>
        </Reference>
        <Reference Include="Comfort.Unity">
            <HintPath>libs\Comfort.Unity.dll</HintPath>
        </Reference>
        <Reference Include="CommonExtensions">
            <HintPath>libs\CommonExtensions.dll</HintPath>
        </Reference>
        <Reference Include="DissonanceVoip, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\DissonanceVoip.dll</HintPath>
        </Reference>
        <Reference Include="DrakiaXYZ-BigBrain">
            <HintPath>libs\DrakiaXYZ-BigBrain.dll</HintPath>
        </Reference>
        <Reference Include="ItemComponent.Types">
            <HintPath>libs\ItemComponent.Types.dll</HintPath>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>libs\Newtonsoft.Json.dll</HintPath>
        </Reference>
        <Reference Include="Sirenix.Serialization">
            <HintPath>libs\Sirenix.Serialization.dll</HintPath>
        </Reference>
        <Reference Include="spt-reflection">
            <HintPath>libs\spt-reflection.dll</HintPath>
        </Reference>
        <Reference Include="spt-singleplayer">
            <HintPath>libs\spt-singleplayer.dll</HintPath>
        </Reference>

        <Reference Include="System" />
        <Reference Include="System.Core" />
        <Reference Include="System.Data" />
        <Reference Include="System.Drawing" />
        <Reference Include="System.IO.Compression" />
        <Reference Include="System.IO.Compression.FileSystem" />
        <Reference Include="System.Numerics" />
        <Reference Include="System.Runtime.Serialization" />
        <Reference Include="System.Xml" />
        <Reference Include="System.Xml.Linq" />

        <Reference Include="UnityEngine">
            <HintPath>libs\UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Postprocessing.Runtime">
            <HintPath>libs\Unity.Postprocessing.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>libs\Unity.TextMeshPro.dll</HintPath>
        </Reference>

        <Reference Include="UnityEngine.AIModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\UnityEngine.AIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\UnityEngine.AssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AudioModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\UnityEngine.AudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\UnityEngine.ImageConversionModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule">
            <HintPath>libs\UnityEngine.IMGUIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>libs\UnityEngine.InputLegacyModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputModule">
            <HintPath>libs\UnityEngine.InputModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PhysicsModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\UnityEngine.PhysicsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath>libs\UnityEngine.TextRenderingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>libs\UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>libs\UnityEngine.UIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestAudioModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\UnityEngine.UnityWebRequestModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestWWWModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <HintPath>libs\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <None Include=".editorconfig" />
    </ItemGroup>

    <Target Name="BuildSAINAddon" AfterTargets="Build" Condition="'$(BuildSAINAddon)' != 'false' and '$(IsBuildingSAINAddon)' != 'true'">
        <MSBuild Projects="..\addon\pitFireTeam.SAINAddon.csproj"
                 Targets="Build"
                 Properties="Configuration=$(Configuration);Platform=$(Platform);BuildProjectReferences=false;IsBuildingSAINAddon=true;OutDir=$(OutDir)" />
    </Target>

</Project>
