<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="..\..\SERVER-4.08\Build.props" />
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>pitFireTeam.Server</AssemblyName>
    <RootNamespace>pitTeam.Server</RootNamespace>
    <Version>0.9.1</Version>
    <OutputType>Library</OutputType>
    <SptReferenceConfiguration Condition="'$(SptReferenceConfiguration)' == ''">Debug</SptReferenceConfiguration>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SPTarkov.Common">
      <HintPath>..\..\SERVER-4.08\Libraries\SPTarkov.Common\bin\$(SptReferenceConfiguration)\net9.0\SPTarkov.Common.dll</HintPath>
    </Reference>
    <Reference Include="SPTarkov.DI">
      <HintPath>..\..\SERVER-4.08\Libraries\SPTarkov.DI\bin\$(SptReferenceConfiguration)\net9.0\SPTarkov.DI.dll</HintPath>
    </Reference>
    <Reference Include="SPTarkov.Server.Core">
      <HintPath>..\..\SERVER-4.08\Libraries\SPTarkov.Server.Core\bin\$(SptReferenceConfiguration)\net9.0\SPTarkov.Server.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SemanticVersioning" Version="3.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>
  <Target Name="CopyToServer" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <OutputDll Include="$(ProjectDir)$(OutDir)$(TargetName).dll" />
      <Resources Include="$(ProjectDir)Resources\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(OutputDll)" DestinationFolder="F:\Projects\SPT-Tarkov\SERVER-4.08\SPTarkov.Server\bin\$(Configuration)\net9.0\user\mods\pitFireTeam-ServerMod" />
    <Copy
      SourceFiles="@(Resources)"
      DestinationFolder="F:\Projects\SPT-Tarkov\SERVER-4.08\SPTarkov.Server\bin\$(Configuration)\net9.0\user\mods\pitFireTeam-ServerMod\Resources\%(RecursiveDir)"
      SkipUnchangedFiles="true"
    />
  </Target>
</Project>
